export const SERVER_INSTRUCTIONS = [
  "GPT Repo MCP provides controlled access to approved local repositories. All repository access is scoped by repo_id and repo-relative POSIX paths. Read tools inspect approved repositories; mutating tools are disabled by default and require repo-local config opt-in plus explicit user approval.",
  "Use the smallest number of bounded tool calls needed to complete the task. Reuse results already obtained in the current task; do not repeat unchanged file reads, searches, tree scans, skill reads, or git status checks unless repository state may have changed.",
  "Do not call repo_list_roots when a valid repo_id is already known. For onboarding or broad project understanding, prefer repo_project_brief. For code location, prefer repo_search, then use repo_read_many for a known bounded set of files. Use repo_fetch_file for individual targeted files and use paths, globs, cursors, and limits to keep reads focused.",
  "Local Codex skills may contain useful instructions for specialized, format-sensitive, or workflow-heavy tasks. Use codex_list_skills only when a relevant skill is likely to exist or the user mentions a skill, then read only the most relevant skill with codex_read_skill. Do not enumerate or re-read skills for routine code, git, or simple file tasks.",
  "Gather sufficient context before editing, then batch related writes. Use repo_write_file for a focused single-file change. Use one repo_write_changes call for a cohesive multi-file task, and group multiple same-file edits into one ordered grouped edit. Avoid alternating repeated read and write calls unless verification reveals a new issue.",
  "After writing, prefer one repo_git_review call instead of separate status and diff calls. Use compact review mode for inspection. Use mode=commit_plan only when exact stage, commit, restore, or cleanup payloads are required. For normal reviewed commits prefer repo_write_stage_commit; for reviewed recovery prefer repo_write_recover. Use lower-level git tools only for granular control, staged-only commit, troubleshooting, or when a composite payload is unavailable.",
  "Git mutations are local-only. Never push, pull, reset, checkout, switch, rebase, merge, stash, clean, force, delete branches, or execute shell commands. Always prefer repo_write_* names; legacy repo_git_stage, repo_git_unstage, and repo_git_commit aliases may be hidden. repo_git_restore_paths remains the granular tracked-worktree restore tool.",
  "Use repo_policy_explain only when access is blocked, policy is unclear, or the user asks what is permitted. Never request absolute paths or secrets. Default excludes and secret blocking are enforced by the server.",
  "For ChatGPT handoff or resume-context requests, use repo_write_handoff rather than generic write tools. Handoffs are local-only working context and normally should not be committed. Use normal documentation tools when the user asks for durable public project documentation instead.",
  "Direct implementation with repo_write_file or repo_write_changes is the default when the user asks ChatGPT to edit code. Use Codex task tools only when the user explicitly asks for Codex delegation or a Codex prompt. Use repo_write_codex_task for repo-local Codex runs, repo_prepare_codex_task for chat-copy prompt mode, and repo_codex_review after Codex finishes.",
  "Dry-run is optional, not a required ritual. Use it when the user asks for a preview, risk is unclear, or state is unusual. Omit optional reason by default unless it adds meaningful audit context.",
  "For interrupted workflows, use repo_last_write, then repo_git_review to establish current repository truth before continuing. If an action is needed, request mode=commit_plan before using review-provided mutation payloads.",
  "For large text files, use targeted line ranges, byte offsets, or cursor pagination. Use repo_fetch_image only for approved PNG, JPEG, or WebP files. Nested repositories and submodules are separate trust boundaries and must be registered as their own repo_id before access."
].join(" ");
