@echo off
chcp 65001 >nul
setlocal EnableExtensions EnableDelayedExpansion

REM ============================================================
REM setup-gpt-repo-mcp.cmd
REM One-time or occasional setup: dependency checks, clone,
REM npm install/build. Runtime repository config is disposable
REM and is generated by start-gpt-repo-mcp.cmd.
REM ============================================================

set "TOOLS_DIR=%~dp0"
set "ROOT_DIR=%TOOLS_DIR%.."
set "CONFIG_FILE=%ROOT_DIR%\gpt-repo-mcp.config.json"

if not exist "%CONFIG_FILE%" (
    echo [ERROR] Config file not found:
    echo %CONFIG_FILE%
    pause
    exit /b 1
)

echo.
echo ====== 1. Read setup config ======

for /f "usebackq delims=" %%A in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-Content -Raw '%CONFIG_FILE%' | ConvertFrom-Json).installRoot"`) do set "INSTALL_ROOT=%%A"
for /f "usebackq delims=" %%A in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-Content -Raw '%CONFIG_FILE%' | ConvertFrom-Json).projectDirName"`) do set "PROJECT_DIR_NAME=%%A"
for /f "usebackq delims=" %%A in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-Content -Raw '%CONFIG_FILE%' | ConvertFrom-Json).repoUrl"`) do set "REPO_URL=%%A"
for /f "usebackq delims=" %%A in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-Content -Raw '%CONFIG_FILE%' | ConvertFrom-Json).useTailscaleFunnel"`) do set "USE_TAILSCALE_FUNNEL=%%A"
for /f "usebackq delims=" %%A in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-Content -Raw '%CONFIG_FILE%' | ConvertFrom-Json).autoBuild"`) do set "AUTO_BUILD=%%A"

if "%USE_TAILSCALE_FUNNEL%"=="" set "USE_TAILSCALE_FUNNEL=True"
if "%AUTO_BUILD%"=="" set "AUTO_BUILD=True"

set "PROJECT_DIR=%INSTALL_ROOT%\%PROJECT_DIR_NAME%"

echo INSTALL_ROOT       = %INSTALL_ROOT%
echo PROJECT_DIR        = %PROJECT_DIR%

echo.
echo ====== 2. Check dependencies ======

where node >nul 2>nul
if errorlevel 1 (
    echo [ERROR] node not found. Please install Node.js LTS first.
    pause
    exit /b 1
)

where npm.cmd >nul 2>nul
if errorlevel 1 (
    echo [ERROR] npm.cmd not found. Please reinstall Node.js LTS.
    pause
    exit /b 1
)

where git >nul 2>nul
if errorlevel 1 (
    echo [ERROR] git not found. Please install Git first.
    pause
    exit /b 1
)

if /I "%USE_TAILSCALE_FUNNEL%"=="True" (
    where tailscale >nul 2>nul
    if errorlevel 1 (
        echo [ERROR] tailscale not found. Please install and login to Tailscale first.
        pause
        exit /b 1
    )
)

echo [OK] node:
node -v

echo [OK] npm:
call npm.cmd -v

echo [OK] git:
git --version

echo.
echo ====== 3. Prepare gpt-repo-mcp project ======

if not exist "%INSTALL_ROOT%" (
    echo Create install root:
    echo %INSTALL_ROOT%
    mkdir "%INSTALL_ROOT%"
)

if not exist "%PROJECT_DIR%" (
    echo Project not found. Cloning:
    echo %REPO_URL%
    git clone "%REPO_URL%" "%PROJECT_DIR%"
    if errorlevel 1 (
        echo [ERROR] git clone failed.
        pause
        exit /b 1
    )
) else (
    echo Project directory already exists:
    echo %PROJECT_DIR%
)

cd /d "%PROJECT_DIR%"
if errorlevel 1 (
    echo [ERROR] Cannot enter project directory:
    echo %PROJECT_DIR%
    pause
    exit /b 1
)

if not exist "package.json" (
    echo [ERROR] package.json not found in:
    echo %PROJECT_DIR%
    echo Please check projectDirName in JSON config.
    pause
    exit /b 1
)

echo.
echo ====== 4. Install dependencies and build ======

if /I "%AUTO_BUILD%"=="True" (
    echo Running npm install...
    call npm.cmd install
    if errorlevel 1 (
        echo [ERROR] npm install failed.
        pause
        exit /b 1
    )

    echo Running npm run build...
    call npm.cmd run build
    if errorlevel 1 (
        echo [ERROR] npm run build failed.
        pause
        exit /b 1
    )
) else (
    echo autoBuild=false, skip npm install and npm run build.
)

echo.
echo ====== Setup finished ======
echo Start one-shot runtime with:
echo %ROOT_DIR%\start-gpt-repo-mcp.cmd
echo.
pause

endlocal
exit /b 0
