export const DEFAULT_WRITE_POLICY = {
  enabled: false,
  allowed_globs: [
    ".chatgpt/**",
    ".codex/**",
    "docs/**",
    "README.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "CODE_OF_CONDUCT.md",
    "SUPPORT.md",
    "LICENSE",
    ".gitignore"
  ],
  denied_globs: [
    ".env",
    ".env.local",
    ".env.production",
    ".env.*",
    "**/*.pem",
    "**/*.key",
    ".git/**",
    "node_modules/**",
    "**/node_modules/**",
    "dist/**",
    "**/dist/**",
    "build/**",
    "**/build/**",
    "out/**",
    "**/out/**",
    "coverage/**",
    "**/coverage/**",
    "test-results/**",
    "**/test-results/**",
    "playwright-report/**",
    "**/playwright-report/**",
    ".next/**",
    "**/.next/**",
    ".nuxt/**",
    "**/.nuxt/**",
    ".svelte-kit/**",
    "**/.svelte-kit/**",
    ".astro/**",
    "**/.astro/**",
    ".cache/**",
    "**/.cache/**",
    ".turbo/**",
    "**/.turbo/**",
    ".vercel/**",
    "**/.vercel/**",
    ".venv/**",
    "**/.venv/**",
    "venv/**",
    "**/venv/**"
  ],
  max_bytes_per_write: 1048576
};
